locals {
  ecr_name               = "${terraform.workspace}-${var.suffix}-ecr"
  ecs_cluster_name       = "${terraform.workspace}-${var.suffix}-ecs-cluster"
  ecs_task_name          = "${terraform.workspace}-${var.suffix}-task"
  container_name         = "${terraform.workspace}-${var.suffix}-container-name"
  redis_service_name     = "${terraform.workspace}-${var.suffix}-redis"
  namespace              = "${terraform.workspace}-${var.suffix}.local"
  ecs_service_name       = "${terraform.workspace}-${var.suffix}-service"
  codecommit-name        = "${terraform.workspace}-${var.suffix}-codecommit"
  image_name             = "${terraform.workspace}-${var.suffix}-webapp_image"
  REPOSITORY_URI         = "${var.aws_account_id}.dkr.ecr.${var.REGION}.amazonaws.com/${local.ecr_name}"
  tag                    = "${terraform.workspace}"
  bucket_name            = "${terraform.workspace}-${var.suffix}-codepipeline-artifacts"
  pipeline_name          = "${terraform.workspace}-${var.suffix}-pipeline"
  build-project-name     = "${terraform.workspace}-${var.suffix}-codebuild"
  ecs_service_name_redis = "${terraform.workspace}-${var.suffix}-ecs-service-redis"
  ecs_task_name_redis    = "${terraform.workspace}-${var.suffix}-redis-task"
  security_group_name    = "${terraform.workspace}-${var.suffix}-allow_tls"
  ecs_role               = "${terraform.workspace}-${var.suffix}-ecs_role"
  codebuildpoilicy       = "${terraform.workspace}-${var.suffix}-codebuildpoilicy"
  CodeBuildRole          = "${terraform.workspace}-${var.suffix}-CodeBuildRole"
  codepipeline_role      = "${terraform.workspace}-${var.suffix}-codepipeline_role"
  codepipelinepoilicy    = "${terraform.workspace}-${var.suffix}-codepipelinepoilicy"


}